---
- name: "Criando diretório para servidor arquivo Vagrant..."
  file:
    path: /home/{{ HOME_DIRECTORY }}/vagrantfiles/
    owner: "{{ USER }}"
    group: "{{ GROUP }}"
    state: directory
    mode: '{{ MODE }}'

- name: "Copiando template para o servidor Master01..."
  template: src=Vagrantfile.j2 dest=~/vagrantfiles/Vagrantfile mode="{{ MODE }}" owner="{{ USER }}" group="{{ GROUP }}"


- name: "Rodando deploy dos servidores Vagrant..."
  shell: |
      cd ~/vagrantfiles/
      vagrant up